export const OBTENER_PRODUCTOS = 'OBTENER_PRODUCTOS';

export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO';
export const CONFIMAR_ORDENAR_PLATILLO = 'CONFIMAR_ORDENAR_PLATILLO'

export const MOSTRAR_RESUMEN = 'MOSTRAR_RESUMEN'
export const ELIMINAR_PEDIDO = 'ELIMINAR_PEDIDO'
export const PEDIDO_ORDENADO = 'PEDIDO_ORDENADO'